# Schema for the theme setting configuration file of the THEMETITLE theme.

nrcan_wxt.settings:
  type: theme_settings
  label: 'NRCan WxT settings'
  mapping:
    cdn_provider:
      type: string
      label: 'CDN Provider'
    breadcrumb_home:
      type: integer
      label: 'Breadcrumb Home'
