_core:
  default_config_hash: Cixub1LbvvPWTTlpSrDeGHUY3Pc5r6NKYIGZsrrvxHE
langcode: en
content_health:
  report_button_title: 'Report a problem'
  report_button_text: 'Report a problem or mistake on this page'
  report_button_target_url: 'https://natural-resources.canada.ca/report-problem'
