<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function theme_upgrades_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.theme_upgrades':
      return t('
        <h2>This module includes custom and experimental upgrades.</h2>
        <h3>Instructions</h3>
        <p>Enable the features you\'d like on the admin page.</p>
      ');
  }
}


function theme_upgrades_bootstrap_cards() {
  return \Drupal::config('theme_upgrades.settings')->get('bootstrap_cards') == 'on';
}

function theme_upgrades_flex_menu() {
  return \Drupal::config('theme_upgrades.settings')->get('flex_menu') == 'on';
}

function theme_upgrades_left_menu() {
  return \Drupal::config('theme_upgrades.settings')->get('left_menu') == 'on';
}

function theme_upgrades_admin_css() {
  return \Drupal::config('theme_upgrades.settings')->get('admin_css') == 'on';
}

function theme_upgrades_wet5() {
  return \Drupal::config('theme_upgrades.settings')->get('experimental.wet5') == 'on';
}

function theme_upgrades_block_update_date() {
  return \Drupal::config('theme_upgrades.settings')->get('bootstrap_cards') == 'on';
  return variable_get('theme_upgrades_block_update_date', 'off') == 'on';
}

function theme_upgrades_custom_bullets() {
  return \Drupal::config('theme_upgrades.settings')->get('custom_bullets') == 'on';
}

function theme_upgrades_custom_ga_links() {
  return \Drupal::config('theme_upgrades.settings')->get('custom_ga_links') == 'on';
}

/**
 * Implements hook_init()
 *
 * @link https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_init/7.x
 */
/*function theme_upgrades_init() {
  if (theme_upgrades_bootstrap_cards()) {
    drupal_add_css(drupal_get_path('module', 'theme_upgrades') . '/css/cards.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  }
  if (theme_upgrades_flex_menu()) {
    drupal_add_css(drupal_get_path('module', 'theme_upgrades') . '/css/wet4_internet_menu.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  }
  if (theme_upgrades_left_menu()) {
    drupal_add_css(drupal_get_path('module', 'theme_upgrades') . '/css/wet_left_menu.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  }
  if (theme_upgrades_wet5()) {
    drupal_add_css(drupal_get_path('module', 'theme_upgrades') . '/css/wet5.css', array('weight' => CSS_THEME));
  }
  if (theme_upgrades_custom_bullets()) {
    drupal_add_css(drupal_get_path('module', 'theme_upgrades') . '/css/custom_bullets.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    drupal_add_js(drupal_get_path('module', 'theme_upgrades') . '/js/custom_bullets.js', array('type' => 'file', 'scope' => 'footer', 'group' => JS_LIBRARY, 'every_page' => TRUE, 'defer' => TRUE));
  }
  if (theme_upgrades_custom_ga_links()) {
    //drupal_add_css(drupal_get_path('module', 'theme_upgrades') . '/css/ga_link.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    drupal_add_js(drupal_get_path('module', 'theme_upgrades') . '/js/ga_links.js', array('type' => 'file', 'scope' => 'footer', 'group' => JS_LIBRARY, 'every_page' => TRUE, 'defer' => TRUE));
  }
}*/


/*function theme_upgrades_preprocess_html(&$variables) {
  global $theme;

  // Modify the Admin theme
  if ($theme === variable_get('admin_theme', 'seven')) {
    if (theme_upgrades_admin_css()) {
      drupal_add_css(drupal_get_path('module', 'theme_upgrades') . '/css/admin.css', array('weight' => CSS_THEME));
    }
  }
}*/

/**
 * Implements hook_process_html().
 *
 * Add scripts on overall the site which are defined on the settings page.
 */
/*function theme_upgrades_process_html(&$variables) {
  global $theme;

  // Don't modify the Admin theme
  if ($theme === variable_get('admin_theme', 'seven')) {
    return;
  }

  // WeT5 goes in the footer
  if (theme_upgrades_wet5()) {
    $wet5_require = file_create_url(drupal_get_path('module', 'theme_upgrades').'/wet_boew/stacks/src/require.js');
    $wet5_file = file_create_url(drupal_get_path('module', 'theme_upgrades').'/wet_boew/stacks/src/wb5');
    $variables['page_bottom'] .= '<script src="'.$wet5_require.'" data-main="'.$wet5_file.'"></script>' . PHP_EOL;
  }

}*/

/*function theme_upgrades_redirect_alter($redirect) {
  // If the variable "pdfexport" is passed in the url then trigger pdf mode and
  // block redirects so the page loads even if the url has been redirected.
  if(!empty($_REQUEST['pdfexport']) || !empty($_COOKIE['pdfexport'])) {
    unset($redirect->redirect);
  }
}*/
