cards:
  css:
    theme:
      css/cards.css: {}
osdp:
  css:
    theme:
      css/osdp.css: {}
ngsc:
  css:
    theme:
      css/ngsc.css: {}
minescanada:
  css:
    theme:
      css/minescanada.css: {}
left-menu:
  css:
    theme:
      css/wet_left_menu.css: {}
wet5:
  css:
    theme:
      css/wet5.css: {}
theme-updates-wet5-library:
  js:
    wet_boew/stacks/src/require.js: {}
  dependencies:
    - core/jquery
match-height:
  js:
    match_height/dist/jquery.matchHeight.js: {}
  dependencies:
    - core/jquery
custom-bullets:
  css:
    component:
      css/custom_bullets.css: {}
  js:
    js/custom_bullets.js: {}
  dependencies:
    - core/jquery
custom-ga-links:
  js:
    js/ga_links.js: {}
  dependencies:
    - core/jquery
