name: 'Theme Settings (Cards, Custom Themes, etc)'
type: module
description: 'Backport of the Bootstrap v4 cards, Menu update for Web Usibility, Wet5 demo and more.'
core_version_requirement: ^8.8 || ^9
package: 'NRCan'
configure: theme_settings.config
