<?php


use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nrcan_adobeanalytics_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.nrcan_adobeanalytics':
      return t('
        <h2>NRCan Adobe Analytics</h2>
        <h3>Instructions</h3>

        <p>Lorem ipsum dolor sit amet... </p>
      ');
  }
}

function nrcan_adobeanalytics_is_enabled() {
  return \Drupal::config('nrcan_adobeanalytics')->get('enabled') == 'on';
}

/*
 * Implements hook_library_info_alter().
 */
function nrcan_adobeanalytics_library_info_alter(&$libraries, $extension) {
  if ($extension === 'nrcan_adobeanalytics' && isset($libraries['nrcan-adobeanalytics'])) {


  }
}


/**
 * Implements hook_page_attachments()
 *
 */
function nrcan_adobeanalytics_page_attachments(array &$page) {
  if (nrcan_adobeanalytics_is_enabled()) {
    $page['#attached']['library'][] = 'nrcan-adobeanalytics/header';
    $page['#attached']['library'][] = 'nrcan-adobeanalytics/footer';
  }

}


/*
another version... possible reference code
function quickedit_library_info_alter(&$libraries, $extension) {
  if ($extension === 'quickedit' && isset($libraries['quickedit'])) {
    $theme = Drupal::config('system.theme')
      ->get('admin');

    // First let the base theme modify the library, then the actual theme.
    $alter_library = function (&$library, $theme) use (&$alter_library) {
      if (isset($theme) && ($theme_path = drupal_get_path('theme', $theme))) {
        $info = system_get_info('theme', $theme);

        // Recurse to process base theme(s) first.
        if (isset($info['base theme'])) {
          $alter_library($library, $info['base theme']);
        }
        if (isset($info['quickedit_stylesheets'])) {
          foreach ($info['quickedit_stylesheets'] as $path) {
            $library['css']['theme']['/' . $theme_path . '/' . $path] = [];
          }
        }
      }
    };
    $alter_library($libraries['quickedit'], $theme);
  }
}
*/


/**
 * Implements hook_theme().
 */
 /*
function nrcan_adobeanalytics_theme($existing, $type, $theme, $path) {
  $variables = [
    'nrcan_adobeanalytics' => [
      'variables' => [
        'source_text' => NULL,
      ],
      'template' => 'nrcan_adobeanalytics',
    ],
  ];
  return $variables;
}
*/
/**
 * Template preprocess function for Lorem ipsum.
 *
 * @param array $variables
 *   An associative array containing:
 *   - source_text
 */
 /*
function template_preprocess_nrcan_adobeanalytics(&$variables) {
  $punctuation = array('. ', '! ', '? ', '... ', ': ', '; ');
  for ($i = 0; $i < count($variables['source_text']); $i++) {
    $big_text = explode('. ', $variables['source_text'][$i]);
    for ($j = 0; $j < count($big_text) - 1; $j++) {
      $big_text[$j] .= $punctuation[floor(mt_rand(0, count($punctuation) - 1))];
    }
    $variables['source_text'][$i] = implode('', $big_text);
  }
}
*/
