tags:
  dcterms_language: fra
  dcterms_creator: 'Ressources naturelles Canada'
  dcterms_publisher: 'Ressources naturelles Canada'
  canonical_url: '[current-page:url]'
  title: '[current-page:title] | [site:name]'
label: Global
