title: ' Contactez-nous'
elements: |
  name:
    '#title': 'Votre nom'
  email:
    '#title': 'Votre e-mail'
  subject:
    '#title': Sujet
  actions:
    '#submit__label': 'Envoyer le message'
settings:
  confirmation_message: 'Votre message a &eacute;t&eacute; envoy&eacute;.'
handlers:
  email_confirmation:
    label: 'Courriel de confirmation'
    settings:
      from_name: _default
      subject: '[webform_submission:values:subject:raw]'
      body: '[webform_submission:values:message:value]'
  email_notification:
    label: 'Notification par courriel'
    settings:
      from_name: '[webform_submission:values:name:raw]'
      subject: '[webform_submission:values:subject:raw]'
      body: '[webform_submission:values:message:value]'
