site_name:
  en: 'The Canadian Minerals and Metals Plan'
  fr: 'Le Plan canadien pour les minéraux et les métaux'
site_fip:
  en: /sites/minescanada-admin/files/2022-03/cmmp_en.png
  fr: /sites/minescanada-admin/files/2022-03/cmmp_fr.png
splash_bg: ''
tc_link:
  en: ''
  fr: ''
