site_name:
  en: 'National Geological Surveys Committee'
  fr: 'Comite national des commissions geologiques'
splash_bg: ''
tc_link:
  en: ''
  fr: ''
site_fip:
  en: /sites/ngsc/files/2022-01/ngsc-logo-en.png
  fr: /sites/ngsc/files/2022-01/ngsc-logo-fr.png
